const portfolio = {
  projects: [
    {title:'Knowledge-Augmented CVAE',type:'Deep Learning · Research',desc:'A gene perturbation prediction system using PyTorch and BioBERT on large-scale single-cell genomic datasets.',tags:['Python','PyTorch','BioBERT','Deep Learning'],glow:'#a768ff66',details:{problem:'Predicting cellular responses to gene perturbations from complex single-cell genomic data.',built:'Developed an AI-based perturbation prediction system and an evaluation framework for benchmarking model performance.',architecture:'A knowledge-augmented conditional variational autoencoder workflow using transformer-derived BioBERT representations with quantitative model evaluation.',contribution:'Developed the system and built the evaluation framework.',challenges:'Working with large-scale genomic data and comparing model behavior against baselines.',results:'Benchmarked performance using Pearson Correlation, R², and MSE.',lessons:'Applied experience with transformer embeddings, deep learning, LLM concepts, and model evaluation.'}},
    {title:'Speech Recognition System',type:'NLP · Speech',desc:'A multilingual speech-enabled chatbot that processes academic queries in Hindi and English.',tags:['Python','ASR','NLP','Speech Recognition'],glow:'#5b8cff66',details:{problem:'Enable efficient voice-based handling of academic queries across Hindi and English.',built:'Developed a multilingual speech-enabled chatbot with speech-to-text transcription and intent classification.',architecture:'Python-based Automatic Speech Recognition feeding an NLP intent-classification workflow.',contribution:'Implemented speech transcription and intent classification for multilingual academic queries.',challenges:'Handling spoken input across two languages while preserving useful intent signals.',results:'Achieved 90% ASR accuracy.',lessons:'Hands-on experience with speech recognition and NLP pipelines.'}}
  ],
  skills: {
    'Languages':['Java','Python','JavaScript','TypeScript','C','C++','PHP','HTML','CSS'],
    'Full-Stack':['Spring Boot','AngularJS','REST APIs','Microservices','AJAX'],
    'Data & Systems':['SQL','PostgreSQL','MongoDB','Apache Kafka','Distributed Systems'],
    'Cloud & DevOps':['AWS Services','Docker','Linux','Git','Azure DevOps'],
    'AI / ML':['Deep Learning','NLP','Speech Recognition','PyTorch','BioBERT'],
    'Quality':['Unit Testing','Integration Testing','Test Planning'],
    'Engineering Docs':['Software Design Documentation','Requirements Documentation']
  }
};
const rail=document.querySelector('#projectRail');
portfolio.projects.forEach((p,i)=>{const el=document.createElement('article');el.className='project-card reveal';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',`View ${p.title} details`);el.innerHTML=`<div class="project-art" style="--cardGlow:${p.glow}"></div><div class="project-content"><small>${p.type}</small><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div>`;const open=()=>openProject(i);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}});rail.appendChild(el)});
const groups=document.querySelector('#skillGroups');Object.entries(portfolio.skills).forEach(([name,items])=>{groups.insertAdjacentHTML('beforeend',`<article class="skill-group reveal"><h3>${name}</h3><div class="skill-list">${items.map(x=>`<span>${x}</span>`).join('')}</div></article>`)});
const modal=document.querySelector('#projectModal'),modalContent=document.querySelector('#modalContent');
function openProject(i){const p=portfolio.projects[i],d=p.details;modalContent.innerHTML=`<div class="modal-body"><p class="kicker">${p.type}</p><h2>${p.title}</h2><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>${[['Problem',d.problem],['What I Built',d.built],['Architecture',d.architecture],['My Contribution',d.contribution],['Challenges',d.challenges],['Results / Impact',d.results],['Lessons Learned',d.lessons]].map(([h,v])=>`<h3>${h}</h3><p>${v}</p>`).join('')}</div>`;modal.showModal()}
document.querySelector('#modalClose').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
document.querySelector('#nextProject').onclick=()=>rail.scrollBy({left:540,behavior:'smooth'});document.querySelector('#prevProject').onclick=()=>rail.scrollBy({left:-540,behavior:'smooth'});
const menuBtn=document.querySelector('#menuBtn'),mobileMenu=document.querySelector('#mobileMenu');menuBtn.onclick=()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)};mobileMenu.querySelectorAll('a').forEach(a=>a.onclick=()=>{mobileMenu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
addEventListener('scroll',()=>document.querySelector('#nav').classList.toggle('scrolled',scrollY>30),{passive:true});
